<?php
require_once __DIR__ . '/common.php';
hxTestRequireAdmin();
$state = hxTestLoadState();
$price = hxTestCurrentPrice($state);
$active = hxTestOverrideActive($state);
$remaining = $active ? max(0, $state['overrideUntil'] - time()) : 0;
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Harbcoin Trading Simulation</title><link rel="stylesheet" href="test.css"></head>
<body class="hx-test"><header class="topbar"><a class="brand" href="index.php">HarbourX <span>TEST</span></a><nav><a href="admin.php">Price control</a><a href="admin.php?logout=1">Sign out</a></nav></header>
<main class="trade-shell">
  <section class="simulation-warning"><strong>Simulation only</strong><span>Harbcoin is fictional. Prices, balances and orders on this page are not real and cannot be deposited, withdrawn or exchanged.</span></section>
  <section class="market-head"><div class="asset"><i>H</i><div><h1>Harbcoin / Australian Dollar</h1><p>HBC / AUD · Simulated spot market</p></div></div><div class="market-price"><strong id="marketPrice"><?= hxTestMoney($price) ?></strong><span class="<?= $active ? 'override' : 'base' ?>"><?= $active ? 'Admin override · ' . gmdate('i:s', $remaining) . ' left' : 'Base simulation price' ?></span></div></section>
  <div class="trade-grid">
    <section class="chart-panel"><div class="chart-head"><h2>HBC simulated price</h2><span>Last 24 hours</span></div><svg viewBox="0 0 700 300" role="img" aria-label="Illustrative Harbcoin simulated price chart"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#20d7d0" stop-opacity=".24"/><stop offset="1" stop-color="#20d7d0" stop-opacity="0"/></linearGradient></defs><g class="grid-lines"><path d="M55 35H670M55 105H670M55 175H670M55 245H670"/></g><path class="area" d="M55 222 C110 210 130 230 180 195 S250 180 286 194 S345 148 390 157 S465 95 510 118 S590 54 670 72 L670 245 L55 245Z"/><path class="line" d="M55 222 C110 210 130 230 180 195 S250 180 286 194 S345 148 390 157 S465 95 510 118 S590 54 670 72"/><circle cx="670" cy="72" r="6"/><g class="axis"><text x="6" y="39"><?= hxTestMoney($price * 1.08) ?></text><text x="6" y="109"><?= hxTestMoney($price * 1.02) ?></text><text x="6" y="179"><?= hxTestMoney($price * .96) ?></text><text x="6" y="249"><?= hxTestMoney($price * .90) ?></text><text x="55" y="278">00:00</text><text x="205" y="278">06:00</text><text x="355" y="278">12:00</text><text x="505" y="278">18:00</text><text x="625" y="278">Now</text></g></svg><p class="chart-note">The chart is illustrative and moves around the admin-controlled simulation price.</p></section>
    <section class="ticket"><div class="side-tabs"><button class="active" data-side="buy">Buy HBC</button><button data-side="sell">Sell HBC</button></div><div class="available"><span id="balanceLabel">Available AUD</span><strong id="balanceValue">A$10,000.00</strong></div><label id="amountLabel">You spend<div class="input-row"><input id="amount" type="number" min="0" step="0.01" value="1000"><span id="unit">AUD</span></div></label><div class="quote"><div><span id="receiveLabel">You receive</span><strong id="receive">—</strong></div><div><span>Simulation fee</span><strong id="fee">—</strong></div><div><span>Price</span><strong><?= hxTestMoney($price) ?> / HBC</strong></div></div><button class="primary" id="preview">Preview simulated buy</button><div class="notice success preview-note" id="previewNote" hidden>No real order was placed. This is a Harbcoin simulation.</div></section>
  </div>
  <section class="panel recent"><div class="section-head"><h2>Simulated orders</h2><span>Demo account only</span></div><table><thead><tr><th>Side</th><th>Amount</th><th>Price</th><th>Total</th><th>Status</th></tr></thead><tbody><tr><td class="green">Buy</td><td>12.000 HBC</td><td><?= hxTestMoney($price * .94) ?></td><td><?= hxTestMoney(12 * $price * .94) ?></td><td>Completed</td></tr><tr><td class="red">Sell</td><td>4.500 HBC</td><td><?= hxTestMoney($price * .98) ?></td><td><?= hxTestMoney(4.5 * $price * .98) ?></td><td>Completed</td></tr></tbody></table></section>
</main>
<script>const price=<?= json_encode($price) ?>,remaining=<?= json_encode($remaining) ?>;let side='buy';const amount=document.getElementById('amount'),receive=document.getElementById('receive'),fee=document.getElementById('fee');function render(){const v=Math.max(0,Number(amount.value)||0),buy=side==='buy';document.getElementById('balanceLabel').textContent=buy?'Available AUD':'Available HBC';document.getElementById('balanceValue').textContent=buy?'A$10,000.00':'80.000 HBC';document.getElementById('amountLabel').firstChild.textContent=buy?'You spend':'You sell';document.getElementById('unit').textContent=buy?'AUD':'HBC';document.getElementById('receiveLabel').textContent=buy?'You receive':'Estimated proceeds';receive.textContent=buy?`${((v*.995)/price).toFixed(3)} HBC`:`A$${(v*price*.995).toFixed(2)}`;fee.textContent=buy?`A$${(v*.005).toFixed(2)}`:`${(v*.005).toFixed(3)} HBC`;document.getElementById('preview').textContent=`Preview simulated ${side}`;document.getElementById('previewNote').hidden=true;}document.querySelectorAll('[data-side]').forEach(b=>b.addEventListener('click',()=>{side=b.dataset.side;document.querySelectorAll('[data-side]').forEach(x=>x.classList.toggle('active',x===b));amount.value=side==='buy'?'1000':'5';render();}));amount.addEventListener('input',render);document.getElementById('preview').addEventListener('click',()=>document.getElementById('previewNote').hidden=false);if(remaining>0)setTimeout(()=>location.reload(),(remaining+1)*1000);render();</script></body></html>
